# Generated by Django 3.1.7 on 2021-03-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20210330_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='id',
        ),
        migrations.AlterField(
            model_name='orders',
            name='consignment_id',
            field=models.IntegerField(auto_created=True, primary_key='consignment_id', serialize=False),
        ),
    ]
