# Generated by Django 3.1.7 on 2021-03-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20210330_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.FloatField(verbose_name=models.FloatField()),
        ),
    ]
