# Generated by Django 3.1.7 on 2021-03-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20210330_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='from_place',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
